name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with environment variables
        run: npm run build
        env:
          # 这里设置的环境变量会在构建时被注入！
          VITE_GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VITE_APP_ID: ${{ secrets.APP_ID }}
          VITE_APP_SECRET: ${{ secrets.APP_SECRET }}

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Debug - Check filesystem
        run: |
          echo "当前工作目录:"
          pwd
          echo "所有文件:"
          ls -la
          echo "Dist 目录详细内容:"
          find dist/ -type f -name "*" | head -20
          echo "文件大小:"
          du -sh dist/ || echo "无法计算大小"
          [ -f "dist/js/config.js" ] && echo "✓ config.js 存在" || echo "✗ config.js 不存在"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'dist'


  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 