name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 设置环境变量
      - name: Setup config
        run: |
          GH_TOKEN=${{ secrets.PAT }} \
          node js/setup-config.js
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./